### ISSUE TITLE
Add a convenience function that tells us if egui wants to handle an event

### ISSUE THREAD

**Issue by derivator** [hasenbanck/egui_winit_platform#11]
Egui already tells us if it wants keyboard or mouse input, but it would be nice if the integration could sort out for us which winit events that includes. See this [prior art](https://github.com/michaelfairley/rust-imgui-sdl2/blob/dc05ed24f21737dde94ca09cd6ae62b0cba0b0b2/src/lib.rs#L71) for imgui. This is useful to be able to do other stuff with events that egui doesn't care about. If this is something that you would like to see, I could try making a pull request.

**Comment by hasenbanck** [comment]
I have no string feeling for or against the solution. Since this crate is very community driven anyhow, PRs are always welcome. I only pay special attention that features that are not essential and need special dependencies, are marked optional.
