### ISSUE TITLE
Support zooming

### ISSUE THREAD

**Issue by zachreizner** [hasenbanck/egui_winit_platform#25]
Unlike the egui_glium platform, this platform doesn't seem to support [zoom input](https://docs.rs/egui/0.13.1/egui/struct.InputState.html#method.zoom_delta). [This code](https://docs.rs/egui_glium/0.13.1/src/egui_glium/lib.rs.html#201) from the glium backend seems directly portable to this platform.

**Comment by hasenbanck** [comment]
You are free to add the missing functionality in a PR if you need it upstreamed.
